name: MilitaryFun
version: '${project.version}'
main: me.fek.militaryfun.MilitaryFun
api-version: 1.18
authors: [ Fek ]
commands:
  configview:
    description: OverView of configuration file
    usage: /<command>
    aliases: conv
